function [data]= CECmodel(data)
global modPV CECheat eleDim
ssccall('data_set_number', data, 'cec_area', modPV.mod_area);
ssccall('data_set_number', data, 'cec_a_ref', modPV.nonideal);
ssccall('data_set_number', data, 'cec_adjust', modPV.t_adjust);
ssccall('data_set_number', data, 'cec_alpha_sc', modPV.alpha_sc);
ssccall('data_set_number', data, 'cec_beta_oc', modPV.beta_oc);
ssccall('data_set_number', data, 'cec_gamma_r', modPV.gamma_r);
ssccall('data_set_number', data, 'cec_i_l_ref', modPV.light_I);
ssccall('data_set_number', data, 'cec_i_mp_ref', modPV.Imp);
ssccall('data_set_number', data, 'cec_i_o_ref', modPV.sat_I);
ssccall('data_set_number', data, 'cec_i_sc_ref', modPV.Isc);
ssccall('data_set_number', data, 'cec_n_s', modPV.cells);
ssccall('data_set_number', data, 'cec_r_s', modPV.r_s);
ssccall('data_set_number', data, 'cec_r_sh_ref', modPV.r_sh);
ssccall('data_set_number', data, 'cec_t_noct', modPV.noct);
ssccall('data_set_number', data, 'cec_v_mp_ref', modPV.Vmp);
ssccall('data_set_number', data, 'cec_v_oc_ref', modPV.Voc);
ssccall('data_set_number', data, 'cec_temp_corr_mode', CECheat.temp_corr_model);
ssccall('data_set_number', data, 'cec_standoff', CECheat.standoff);
ssccall('data_set_number', data, 'cec_height', CECheat.cec_height);
ssccall('data_set_number', data, 'cec_mounting_config', CECheat.mounting_config);
ssccall('data_set_number', data, 'cec_heat_transfer', CECheat.heat_transfer);
ssccall('data_set_number', data, 'cec_mounting_orientation', CECheat.mounting_orientation);
ssccall('data_set_number', data, 'cec_gap_spacing', eleDim.gapSpacing);
ssccall('data_set_number', data, 'cec_module_length', modPV.module_length);
ssccall('data_set_number', data, 'cec_module_width', modPV.module_width);
ssccall('data_set_number', data, 'cec_array_rows', eleDim.vertModules);
ssccall('data_set_number', data, 'cec_array_cols', (4/eleDim.vertModules)*modPV.mps);
ssccall('data_set_number', data, 'cec_backside_temp', 20);% questionable parameter